name: treescape
description: "Cut some trees get some logs."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.9.2
  flame: ^1.30.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.0.0
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/entities/
    - assets/images/sprites/
    - assets/images/sprites/character/
    - assets/images/sprites/character/standard/
    - assets/images/sprites/character/standard/idle/
    - assets/images/sprites/character/standard/walk/
    - assets/images/sprites/character/standard/slash/
    - assets/images/sprites/character/tools/
    - assets/images/sprites/character/tools/fishing/
    - assets/images/sprites/character/tools/slash/
    - assets/images/sprites/character/tools/thrust/
    - assets/images/tiles/
    - assets/images/ui/
    - assets/images/ui/bar/
    - assets/images/ui/bar/icons/
    - assets/images/ui/bar/skills/
